local     all          all                        trust
hostssl   query_cave   query_cave_reader   0.0.0.0/0   cert clientcert=verify-full map=query_cave_reader_map clientname=DN
hostssl   query_cave   query_cave_reader   ::/0        cert clientcert=verify-full map=query_cave_reader_map clientname=DN
hostssl   query_cave   query_cave_admin    0.0.0.0/0   cert clientcert=verify-full map=query_cave_admin_map clientname=DN
hostssl   query_cave   query_cave_admin    ::/0        cert clientcert=verify-full map=query_cave_admin_map clientname=DN
hostnossl all          all                 0.0.0.0/0   reject
hostnossl all          all                 ::/0        reject
hostssl   all          all                 0.0.0.0/0   reject
hostssl   all          all                 ::/0        reject
